#!/bin/bash

readonly SCRIPT_NAME=${0##*/}
readonly VERSION=0.1.0

print_help()
{
    cat << END
   ■■    ■■■■■   ■■■  ■■■■■    ■■    
   ■■    ■      ■     ■   ■■   ■■    
  ■■ ■   ■      ■     ■    ■  ■■ ■   
  ■  ■   ■■■■■  ■■■   ■   ■■  ■  ■   
 ■■  ■■  ■        ■■■ ■■■■■  ■■  ■■  
 ■■■■■■  ■          ■ ■      ■■■■■■  
 ■    ■■ ■         ■■ ■      ■    ■■ 
■■     ■ ■■■■■  ■■■■  ■     ■■     ■
This program is lapper program of SSERAFIM. This makes SSERAFIM analyze multi spicies.
This program depends on SSERAFIM. Please install SSERAFIM and pass through.
If you want to choose another parameters in each process, please rewrite programs by yourself.
<build mode>
Example
    aespa build [OPTION] [-t SRR_TABLE_PATH] [-o OUTPUT_DIR]
OPTION
-o OUTPUT_DIR       Set output directory(default: ./AESPA)
#########################################################
CAUTION : YOU HAVE TO SET THESE PARAMETERS ABSOLUTELY!!
>>better absolute path than relative path<<
#########################################################
-t SRR_TABLE_PATH (.txt)
#########################################################
-c CONDA_INIT_PATH  If SSERAFIM printed error "you have to check ...", please reset path.
                    "~/{YOUR CONDA PACKAGE}/etc/profile.d/conda.sh"
-h HELP             Show help                 
-V VERSION          Show version
<run mode>
Example
    <Both pair-end and single-end>
    aespa run [OPTION] [-o OUTPUT_DIR] [-@ PALARREL]
    [-g SINGLE-END_REFERENCE_GENNOME_PATH_FILE] [-G PAIR_END_REFERENCE_GENNOME_PATH_FILE_PAIR] 
    [-a SINGLE-END_ANNOTATION_PATH_FILE] [-A PAIR-END_ANNOTATION_PATH_FILE]
    <Only pair-end>
    aespa run [OPTION] [-o OUTPUT_DIR] [-@ PALARREL]
    [-G PAIR_END_REFERENCE_GENNOME_PATH_FILE_PAIR] [-A PAIR-END_ANNOTATION_PATH_FILE]
    <Only single-end>
    aespa run [OPTION] [-o OUTPUT_DIR] [-@ PALARREL]
    [-g SINGLE-END_REFERENCE_GENNOME_PATH_FILE] [-a SINGLE-END_ANNOTATION_PATH_FILE]
OPTION
-o OUTPUT_DIR       Set output directory(default: ./AESPA)
* Please set same directory you set when you executed "aespa build" command.
#########################################################
CAUTION : YOU HAVE TO SET THESE PARAMETERS DEPENDING ON YOUR SITUATION!!
>>better absolute path than relative path<<
#########################################################
-g SINGLE-END_REFERENCE_GENNOME_PATH_FILE (.txt)
-a SINGLE-END_ANNOTATION_PATH_FILE (.txt)
-G PAIR_END_REFERENCE_GENNOME_PATH_FILE_PAIR (.txt)
-A PAIR-END_ANNOTATION_PATH_FILE (.txt)
#########################################################
-S SSERAFIM_PATH    Sserafim path
-c CONDA_INIT_PATH  If printed error "you have to check ...",please reset path.
                    "~/{YOUR CONDA PACKAGE}/etc/profile.d/conda.sh"
-@ PARALLEL (int)   Set using CPU core(default: 1)
-L LIGHT_MODE       Don't make law_data.tar.gz (This option work on SSERAFIM)
-h HELP             Show help                 
-V VERSION          Show version
END
}

print_version()
{
    cat << END
${SCRIPT_NAME} version $VERSION
END
}

print_short_help()
{
    cat << END
<build mode>
Example
    aespa build [OPTION] [-t SRR_TABLE_PATH] [-o OUTPUT_DIR]
OPTION
-o OUTPUT_DIR       Set output directory(default: ./AESPA)
#########################################################
CAUTION : YOU HAVE TO SET THESE PARAMETERS ABSOLUTELY!!
>>better absolute path than relative path<<
#########################################################
-t SRR_TABLE_PATH (.txt)
#########################################################
-c CONDA_INIT_PATH  If SSERAFIM printed error "you have to check ...", please reset path.
                    "~/{YOUR CONDA PACKAGE}/etc/profile.d/conda.sh"
-h HELP             Show help                 
-V VERSION          Show version
<run mode>
Example
    <Both pair-end and single-end>
    aespa run [OPTION] [-o OUTPUT_DIR] [-@ PALARREL]
    [-g SINGLE-END_REFERENCE_GENNOME_PATH_FILE] [-G PAIR_END_REFERENCE_GENNOME_PATH_FILE_PAIR] 
    [-a SINGLE-END_ANNOTATION_PATH_FILE] [-A PAIR-END_ANNOTATION_PATH_FILE]
    <Only pair-end>
    aespa run [OPTION] [-o OUTPUT_DIR] [-@ PALARREL]
    [-G PAIR_END_REFERENCE_GENNOME_PATH_FILE_PAIR] [-A PAIR-END_ANNOTATION_PATH_FILE]
    <Only single-end>
    aespa run [OPTION] [-o OUTPUT_DIR] [-@ PALARREL]
    [-g SINGLE-END_REFERENCE_GENNOME_PATH_FILE] [-a SINGLE-END_ANNOTATION_PATH_FILE]
OPTION
-o OUTPUT_DIR       Set output directory(default: ./AESPA)
* Please set same directory you set when you executed "aespa build" command.
#########################################################
CAUTION : YOU HAVE TO SET THESE PARAMETERS DEPENDING ON YOUR SITUATION!!
>>better absolute path than relative path<<
#########################################################
-g SINGLE-END_REFERENCE_GENNOME_PATH_FILE (.txt)
-a SINGLE-END_ANNOTATION_PATH_FILE (.txt)
-G PAIR_END_REFERENCE_GENNOME_PATH_FILE_PAIR (.txt)
-A PAIR-END_ANNOTATION_PATH_FILE (.txt)
#########################################################
-S SSERAFIM_PATH    Sserafim path
-c CONDA_INIT_PATH  If printed error "you have to check ...",please reset path.
                    "~/{YOUR CONDA PACKAGE}/etc/profile.d/conda.sh"
-@ PARALLEL (int)   Set using CPU core(default: 1)
-L LIGHT_MODE       Don't make law_data.tar.gz
-h HELP             Show help                 
-V VERSION          Show version
END
}

SCRIPT_DIR=$(cd $(dirname $0); pwd)

if [[ "$1" == "build" ]] ; then

    #acquire arguments
    args=${@:2}
    #build
    bash $SCRIPT_DIR/script/build.sh $args
    #deal with error 
    if [ $? -ne 0 ]; then
    exit 1
    fi

elif [[ "$1" == "run" ]] ; then

    #acquire arguments
    args=${@:2}
    #build
    bash $SCRIPT_DIR/script/run.sh $args
    #deal with error 
    if [ $? -ne 0 ]; then
    exit 1
    fi

elif [[ "$1" == "-h" ]] ; then
    print_help
    exit 0

elif [[ "$1" == "-V" ]] ; then
    print_version
    exit 0

else 
    printf '%s\n%s\n' "${SCRIPT_NAME}: please select \"build\" or \"run\"" "or input -h, -V option." 1>&2
    print_short_help
    exit 1
fi
