#!/bin/bash

readonly SCRIPT_NAME=${0##*/}
readonly VERSION=0.1.0

print_help()
{
    cat << END
   ■■    ■■■■■   ■■■  ■■■■■    ■■    
   ■■    ■      ■     ■   ■■   ■■    
  ■■ ■   ■      ■     ■    ■  ■■ ■   
  ■  ■   ■■■■■  ■■■   ■   ■■  ■  ■   
 ■■  ■■  ■        ■■■ ■■■■■  ■■  ■■  
 ■■■■■■  ■          ■ ■      ■■■■■■  
 ■    ■■ ■         ■■ ■      ■    ■■ 
■■     ■ ■■■■■  ■■■■  ■     ■■     ■
This program is lapper program of SSERAFIM. This makes SSERAFIM analyze multi spicies.
This program depends on SSERAFIM. Please install SSERAFIM and pass through.
If you want to choose another parameters in each process, please rewrite programs by yourself.
END
}

print_version()
{
    cat << END
${SCRIPT_NAME} version $VERSION
END
}

print_short_help()
{
    cat << END
test version.
END
}

SCRIPT_DIR=$(cd $(dirname $0); pwd)

if [[ "$1" == "build" ]] ; then

    #acquire arguments
    args=${@:2}
    #build
    bash $SCRIPT_DIR/script/build.sh $args
    #deal with error 
    if [ $? -ne 0 ]; then
    exit 1
    fi

elif [[ "$1" == "run" ]] ; then

    #acquire arguments
    args=${@:2}
    #build
    bash $SCRIPT_DIR/script/run.sh $args
    #deal with error 
    if [ $? -ne 0 ]; then
    exit 1
    fi

elif [[ "$1" == "-h" ]] ; then
    print_help
    exit 0

elif [[ "$1" == "-V" ]] ; then
    print_version
    exit 0

else 
    printf '%s\n%s\n' "${SCRIPT_NAME}: please select \"build\" or \"run\"" "or input -h, -V option." 1>&2
    print_short_help
    exit 1
fi
