#!/bin/bash

CONDA_INIT_PATH=$1
OUTPUT_DIR=$2
SCRIPT_DIR=$3
GENNOME_PATH_FILE_PAIR=$4
ANNOTATION_PATH_FILE_PAIR=$5

source $CONDA_INIT_PATH

conda activate bio

python -B $SCRIPT_DIR/create_path_df.py $OUTPUT_DIR $GENNOME_PATH_FILE_PAIR $ANNOTATION_PATH_FILE_PAIR
